useLogging: True

mysql:
  user: awen
  password: '123456'
  host: 121.5.62.4
  port: 3306
  db: DispatchDatabase
  charset: utf8
  autocommit: True
  maxsize: 10
  minsize: 1

neo4j:
  DATABASE_URL: 'bolt://neo4j:zaw1219..@121.5.62.4:7687'

sqlalchemy:
  url: 'mysql+pymysql://awen:123456@121.5.62.4/DispatchDatabase?charset=utf8mb4'
  echo: True
  pool_size: 10
  max_overflow: 10
  connect_args: {'connect_timeout': 10}
